### ISSUE TITLE
Doesn't work with Firefox OSX

### ISSUE THREAD

**Issue by DarKDinDoN** [illandril/FoundryVTT-hotbar-uses#12]
Hello,

Although the module is working great with Chrome on OSX, it doesn't with FF

![Capture d’écran 2020-09-08 à 13 00 03](https://user-images.githubusercontent.com/1687854/92468360-55513400-f1d3-11ea-8ef2-ed8fe0405a88.png)

On the screenshot, there are two hotbars. First one is default FoundryVTT and second one is from the Custom Hotbar Module. The default FoundryVTT doesn't display charges left.

OSX 10.14.6
FF 80.0.1 (64 bits)

**Comment by illandril** [comment]
This is a compatibility issue with Custom Hotbar (#74). I am planning on implementing a workaround for the issue, but it is possible Norc may update Custom Hotbar before I am able to do so.

**Comment by DarKDinDoN** [comment]
@illandril Ah ok, wasn't obvious cause that's actually not the custom hotbar that is not working but the default FoundryVTT one 😄 

Thx!
