### ISSUE TITLE
Compatibility with module hotbar-expension

### ISSUE THREAD

**Issue by DarKDinDoN** [illandril/FoundryVTT-hotbar-uses#16]
Hello,

Is it possible to make this module compatible with https://github.com/ironmonk88/hotbar-expansion?
Thx

**Comment by illandril** [comment]
This requires a change to Monk's Hotbar Expansion. If they accept my pull request (or provide an alternative hook that gives me the information I need), this functionality will be added.

**Comment by ironmonk88** [comment]
Added the code, pushed a new release.  Looking forward to the updates.  :-)

**Comment by DarKDinDoN** [comment]
Great! Thx guys 😄
