### ISSUE TITLE
Add support for Pathfinder 2

### ISSUE THREAD

**Issue by illandril** [illandril/FoundryVTT-hotbar-uses#18]
Add support for showing uses using the Pathfinder 2 (pf2e) module

**Comment by djmove1981** [comment]
Don't know if anybody else asked for it, but it would be nice if your module "Illandril's Hotbar Uses" would support PF2e. Just started playing around with Foundry a week ago, and I definitely see this useful to my players (especially our resident ranger shooting arrows like there's no tomorrow and has issue tracking his arrows).

**Comment by illandril** [comment]
@djmove1981 PF2e, unfortunately, handles a number of things related to uses counting than DnD5e (the system I actually play and understand the most) and PF1e (the other system I think I've got working). Since I don't play PF2e, there's the overhead of me having to actually learn the system on top of deciphering how the system author's implemented it for Foundry.

If you could send me details on a few macros you'd expect to be able to see Uses for, including any details on how someone would manually check to see how many uses are left for the items/actions for behind those macros (and, in situations like ammunition where you can, for example, only use a bow as many times as you have arrows left, how the bow gets linked to the arrows to know that the arrows are what should be used for that item, as opposed to some other ammunition), that would be helpful in making sure I make the support correct and complete.
Even better, if you could set up a world with a variety of macros on the Hotbar, and could zip it up and send it to me with details on what you'd expect the uses values to be for each macro, that would be great (note: user passwords are stored in plain text in the world directory, so if you do this make sure to not send me a world with user passwords unless you scrub those passwords out of the data first).

You can either share the info here or send it to me over email (foundry-modules@illandril.net) or on discord (joespan#3152).

**Comment by illandril** [comment]
@djmove1981 Version 2.3.0 has at least basic PF2e support, but since I don't play PF2e, I'm not sure I've added counts to enough things to fit the needs of PF2e players. If you find anything lacking, please give me more details (see above for the kind of information that would help most). If you try it out and think it's complete, please let me know that too.

**Comment by djmove1981** [comment]
Hey there,

Sorry that I wasn’t able to follow up with your previous reply. Been kind of busy with looking for a new appartment. I’ll definitely take a look and give you my thoughts on it. Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by djmove1981** [comment]
So, tried out a bunch of different consumables (including ammunition) on a test actor, and it works really well. The item description is pasted in the chat, with a use the item button. As soon as it's pressed, it decreases the consumable. Thanks!
