### ISSUE TITLE
animated border appears broken

### ISSUE THREAD

**Issue by EsotericOdyssey** [illandril/FoundryVTT-hotbar-uses#21]
![animation_weirdness](https://user-images.githubusercontent.com/78229350/107727974-b1f0d780-6cba-11eb-8383-1d814f2084db.gif)
I messed around with different border thicknesses and animation speeds and stuff, but the animated border glow keeps doing this specific thing where it flickers/fades in the bottom corner

**Comment by illandril** [comment]
My module doesn't have animated borders. What module were you using to do this, and what settings for that module?

**Comment by illandril** [comment]
@EsotericOdyssey it appears you are using the Macro Marker module to do this. I did not see this same behavior when testing that module with this one, and your screenshot doesn't show any uses indicators, making it extremely unlikely that anything this module is doing is contributing to the issue. You should report this issue on the Macro Marker module project: https://github.com/League-of-Foundry-Developers/foundry-macro-marker

**Comment by EsotericOdyssey** [comment]
(really sorry about this it was late and I got confused)
