### ISSUE TITLE
Compatibility with BetterRolls

### ISSUE THREAD

**Issue by DarKDinDoN** [illandril/FoundryVTT-hotbar-uses#28]
Hello,

This module isn't compatible with BetterRolls anymore.
They changed their macro format:

```javascript
const actorId = "Mr1GJN5k3OaTMXMx";
const itemId = "8DEGgA7hWPkH8Zt2";
const actorToRoll = canvas.tokens.placeables.find(t => t.actor?.id === actorId)?.actor ?? game.actors.get(actorId);
const itemToRoll = actorToRoll?.items.get(itemId);
if (!itemToRoll) {
	return ui.notifications.warn(game.i18n.format("DND5E.ActionWarningNoItem", { item: itemId, name: actorToRoll?.name ?? "[Not Found]" }));
}

return itemToRoll.roll({ vanilla: false });
```

**Comment by illandril** [comment]
I supposed that's one way to make sure your macros still work after someone disabled your module... but I've got a feeling this isn't going to be a stable macro format. I could definitely see any attempt I make to match against this to either fail in future BetterRolls releases and/or start matching macros that really shouldn't have usage calculations attached to them.

I'll need to think about this some to decide if I want to try to create a regex to match against this within my module or if I want to give BetterRolls a pull request to add appropriate `HotbarUsesGeneric` comments to these macros on their end.
