### ISSUE TITLE
[FEATURE] Support for Toolkit13 (13th Age)

### ISSUE THREAD

**Issue by tbrockwood** [illandril/FoundryVTT-hotbar-uses#29]
Hi,
I was wondering if you could add support for the 13th Age System (listed as "Toolkit 13 Character Sheet" in Foundry's Systems). 

Thanks

**Comment by illandril** [comment]
It looks like uses calculation for 13th Age is fairly simple... but I don't know the 13th Age system, so there is a very good chance I overlooked some cases that should be calculating in a different way than I implemented. If something isn't calculating as expected, let me know the details and I'll enhance the 13th Age support.
