### ISSUE TITLE
Support with foundry v9.X

### ISSUE THREAD

**Issue by CaosFR** [illandril/FoundryVTT-hotbar-uses#31]
Hi,

Simple question that many would like to know. Is your module compatible with v9.X? Have any tests been carried out?

I'm refer to : https://docs.google.com/spreadsheets/d/1ppPR348igxL75M_G7dWl3otzXYpPwrnj7NVSDP8GmVw/edit#gid=0

Thanks
Bests regards

**Comment by illandril** [comment]
I have not yet tested any of my modules with v9. I likely won't have enough time to test and make any necessary fixes to support v9 for another week or two.
It is possible that it will just work, so you can try if you want, but I can't guarantee it will work with v9 at this time.

Traduction de Google en français:
> Je n'ai encore testé aucun de mes modules avec la v9.  Je n'aurai probablement pas assez de temps pour tester et apporter les correctifs nécessaires pour prendre en charge la v9 pendant une semaine ou deux.
> Il est possible que cela fonctionne, vous pouvez donc essayer si vous le souhaitez, mais je ne peux pas garantir que cela fonctionnera avec la v9 pour le moment.

**Comment by CaosFR** [comment]
Thanks for your reply. I will waiting, no problem.

**Comment by illandril** [comment]
This module did work in v9 without needing any changes.

**Comment by CaosFR** [comment]
Very good news :) Thanks.
