### ISSUE TITLE
Doesn't work if the macro's format isn't perfect

### ISSUE THREAD

**Issue by Jonwh25** [illandril/FoundryVTT-hotbar-uses#4]
Seems to require you to have Minor-QOL.

I'm using midi-qol and my macro for lucky looks like this:
game.dnd5e.rollItemMacro("Lucky (Halfling)")

The Minor-QOL looks like this and works:
MinorQOL.doRoll(event, "Lucky (Halfling)", {type: "feat", versatile: false});

**Comment by illandril** [comment]
This module doesn't require Minor-QOL, and works with macros created when using no other modules as well as when using Midi QOL. The reason your macro isn't showing the counts is that it's missing the trailing semicolon.

I'm going to update the macro matching to allow for the missing semicolon (as well extra whitespace and replacing the double-quotes with single-quotes or back-ticks).
