### ISSUE TITLE
Ammunition and spontaneous casters can't see values in pf1e

### ISSUE THREAD

**Issue by NickOfSon** [illandril/FoundryVTT-hotbar-uses#40]
From Host (GM) side all is good and no issues, everything works as should be but from the client (player) side issue still persists, they can't see ammunition value or spells and can confirm it by double-checking it via Foundry itself and google chrome. However, prepared casters don't experience issues with spells value. Creating a new actor doesn't fix this issue.

Version of this module: latest 3.0.4
Foundry Version: 11.311
System Name and Version: Pathfinder 1e 9.4
Browser Name and Version: Google Chrome 117.0.5938.132

**Comment by illandril** [comment]
I cannot reproduce this issue. Uses for spells, weapons with ammunition set, and items with charges are all showing correctly for me as both GM and player.

Please clear your browser's cache and see if you can still see the issue.

If so, can you export both the actor(s) and macro(s) you're having a problem with so I can investigate further?

**Comment by NickOfSon** [comment]
It looks like one of my modules does break showing max value for ammunition gonna investigate it further, thanks a lot for your help!

**Comment by NickOfSon** [comment]
![bug](https://github.com/illandril/FoundryVTT-hotbar-uses/assets/85431268/f8f4120b-87b7-417e-817c-d1ebf40c1727)
Found interesting behavior

**Comment by NickOfSon** [comment]
[actor.txt](https://github.com/illandril/FoundryVTT-hotbar-uses/files/12789849/actor.txt)
I couldn't send an actor in json file, so had to create txt one
